-- AlterTable
ALTER TABLE "Photo" ALTER COLUMN "latitude" SET DATA TYPE DECIMAL(20,16),
ALTER COLUMN "longitude" SET DATA TYPE DECIMAL(20,16),
ALTER COLUMN "tripId" SET DATA TYPE TEXT,
ALTER COLUMN "userId" SET DATA TYPE TEXT;
